export const MainBannerImages = [
  {
    id: 1,
    src: "/images/main_banner_img_01.png",
    alt: "러쉬메인배너이미지1",
    eyeText1: "엡전용",
    eyeText2: "사은품",
    Btext1: "연휴맞이",
    Btext2: "더블찬스",
    Stext: "연휴에도 선물도 2배! 향기도 2배!",
  },
  {
    id: 2,
    src: "/images/main_banner_img_02.png",
    alt: "러쉬메인배너이미지2",
    eyeText1: "전시",
    eyeText2: "이벤트",
    Btext1: "K-낫랩",
    Btext2: "출시기념",
    Stext: "전유현 작가 초대전 관람하고 이벤트 참여하기!",
  },
  {
    id: 3,
    src: "/images/main_banner_img_03.png",
    alt: "러쉬메인배너이미지3",
    eyeText1: "취향사전",
    eyeText2: "이벤트",
    Btext1: "보습이",
    Btext2: "필요한 이유",
    Stext: "몸을 촉촉하게 아껴주세요",
  },
  {
    id: 4,
    src: "/images/main_banner_img_04.png",
    alt: "러쉬메인배너이미지4",
    eyeText1: "리미티드",
    eyeText2: "신제품",
    Btext1: "미리 찾아온",
    Btext2: "겨울 친구들",
    Stext: "크리스마스 에디션 론칭!",
  },
  {
    id: 6,
    src: "/images/main_banner_img_06.png",
    alt: "러쉬메인배너이미지6",
    eyeText1: "리미티드",
    eyeText2: "신제품",
    Btext1: "2023",
    Btext2: "윈터 에디션",
    Stext: "로드 오브 미스룰 레인지가 찾아왔어요!",
  },
  {
    id: 7,
    src: "/images/main_banner_img_07.png",
    alt: "러쉬메인배너이미지7",
    eyeText1: "콜라보레이션",
    eyeText2: "이벤트",
    Btext1: "이글이글",
    Btext2: "강렬한 불꽃",
    Stext: "악마의 열매와 함께 떠나는 욕조 속 모험!",
  },
  {
    id: 8,
    src: "/images/main_banner_img_08.png",
    alt: "러쉬메인배너이미지8",
    eyeText1: "리뷰",
    eyeText2: "이벤트",
    Btext1: "스킨케어",
    Btext2: "베스트 리뷰 선발대회!",
    Stext: "스킨케어 제품 리뷰 남기고 깜짝 선물 받기",
  },
  {
    id: 9,
    src: "/images/main_banner_img_09.png",
    alt: "러쉬메인배너이미지9",
    eyeText1: "덕찌",
    eyeText2: "이벤트",
    Btext1: "다운로드",
    Btext2: "러쉬 9월",
    Stext: "데이지가 흩날리는 가을",
  },
];
